NoiThatViet_Nhom3/NoiThatViet_Nhom3/NoiThatViet_Nhom3/Controllers/CartController.cs
using Newtonsoft.Json.Linq;
using System;
using MoMo;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using NoiThatViet_Nhom3.Others;
using NoiThatViet_Nhom3.Models;
using System.IO;
using System.Net.Mail;
using System.Net;
using System.Threading.Tasks;
using MailKit.Search;

namespace NoiThatViet_Nhom3.Controllers
{
    public class CartController : Controller
    {
        // GET: Cart
        [HandleError]
        public ActionResult Index()
        {
            MyDataDataContext Data = new MyDataDataContext();

            var currentAccount = (TaiKhoan)Session["TaiKhoan"];
            if (currentAccount == null)
            {
                return RedirectToAction("DangNhap", "Home");
            }

            int userId = currentAccount.id;

            var gioHang = Data.GioHangs.FirstOrDefault(g => g.id == userId);
            if (gioHang == null)
            {
                ViewBag.Message = "Giỏ hàng của bạn hiện đang trống.";
                return View();
            }

            string cartId = gioHang.MaGioHang;
            var cartItems = Data.ChiTietGioHangs.Where(c => c.MaGioHang == cartId).ToList();
            var cartDetails = new List<CartItemDetail>();

            int tongTien = 0; 

            foreach (var item in cartItems)
            {
                // Lấy thông tin sản phẩm từ bảng SanPham
                var product = Data.SanPhams.FirstOrDefault(p => p.MaSanPham == item.MaSanPham && p.AnHien == "Hiện");

                if (item != null && product != null)
                {
                    // Thêm thông tin chi tiết vào danh sách
                    cartDetails.Add(new CartItemDetail
                    {
                        id = item.MaSanPham,
                        MaGioHang = item.MaGioHang,
                        TenSanPham = product.TenSanPham,
                        Gia = product.Gia,
                        HinhAnh = product.HinhAnh,
                        SoLuong = (int)item.SoLuong,
                        ThanhTien = (decimal)item.ThanhTien
                    });

                    tongTien += (int)item.ThanhTien;
                }
                else
                {
                    continue;
                }
            }


            ViewBag.ChiTietDonHang = cartDetails;
            ViewBag.TongTien = tongTien;

            return View();
        }
        private bool KiemTraKhuyenMai(KhuyenMai khuyenMai)
        {
            DateTime now = DateTime.Now;
            return now >= khuyenMai.ThoiGianBatDau && now <= khuyenMai.ThoiGianKetThuc;
        }
        public ActionResult AddToCart(string id)
        {
            var currentAccount = (TaiKhoan)Session["TaiKhoan"];
            id = id.Trim().Replace("%20", "");
            if (currentAccount == null)
            {
                return Json(new { success = false, message = "Bạn cần đăng nhập để thêm sản phẩm vào giỏ hàng. Vui lòng đăng nhập và thử lại." });
            }

            int accountId = currentAccount.id;
            MyDataDataContext Data = new MyDataDataContext();

            // Xử lý thêm sản phẩm vào giỏ hàng
            var existingCart = Data.GioHangs.FirstOrDefault(g => g.id == accountId);

            string cartId = "";

            if (existingCart == null)
            {
                cartId = GenerateRandomCartId();
                var newCart = new GioHang
                {
                    MaGioHang = cartId,
                    id = accountId

                };
                Data.GioHangs.InsertOnSubmit(newCart);
                Data.SubmitChanges();
            }
            else
            {
                cartId = existingCart.MaGioHang;
            }

            string strId = id.ToString();
            var existingCartItem = Data.ChiTietGioHangs.FirstOrDefault(c => c.MaGioHang == cartId && c.MaSanPham == strId);

            if (existingCartItem == null)
            {
                var product = Data.SanPhams.FirstOrDefault(p => p.MaSanPham == id);

                if (product != null)
                {
                    var khuyenMai = Data.ChiTietKhuyenMais
                                 .Where(ct => ct.MaSanPham == product.MaSanPham)
                                 .Join(Data.KhuyenMais,
                                       ct => ct.MaVoucher,
                                       km => km.MaVoucher,
                                       (ct, km) => new
                                       {
                                           KhuyenMai = km,
                                           ChiTietKhuyenMai = ct
                                       })
                                 .FirstOrDefault();

                    int productPrice = product.Gia; 
                    if (khuyenMai != null && KiemTraKhuyenMai(khuyenMai.KhuyenMai))
                    {
                        // Nếu có khuyến mãi, giảm giá
                        productPrice -= (productPrice * khuyenMai.KhuyenMai.PhanTramGiam) / 100;
                    }

                    var newCartItem = new ChiTietGioHang
                    {
                        MaGioHang = cartId,
                        MaSanPham = strId,
                        SoLuong = 1, 
                        ThanhTien = productPrice 
                    };

                    Data.ChiTietGioHangs.InsertOnSubmit(newCartItem);
                    Data.SubmitChanges();
                    var cartItems = Data.ChiTietGioHangs.Where(c => c.MaGioHang == cartId);
                    int updatedCartItemCount = cartItems.Select(c => c.MaSanPham).Distinct().Count();


                    return Json(new { success = true, message = "Thêm sản phẩm vào giỏ hàng thành công!", cartItemCount = updatedCartItemCount });
                }
                else
                {
                    return Json(new { success = false, message = "Không tìm thấy sản phẩm." });
                }
            }
            else
            {
                existingCartItem.SoLuong++;
                existingCartItem.ThanhTien = existingCartItem.SanPham.Gia * existingCartItem.SoLuong; // Cập nhật thành tiền
                Data.SubmitChanges();

                // Cập nhật tổng số lượng sản phẩm trong giỏ hàng
                var cartItems = Data.ChiTietGioHangs.Where(c => c.MaGioHang == cartId);
                int updatedCartItemCount = cartItems.Count();

                return Json(new { success = true, message = "Thêm sản phẩm vào giỏ hàng thành công!", cartItemCount = updatedCartItemCount });
            }
        }




        [HttpPost]
        public ActionResult AddToCart2(string id, int quantity)
        {
            var currentAccount = (TaiKhoan)Session["TaiKhoan"];
            id = id.Trim().Replace("%20", "");
            if (currentAccount == null)
            {
                return Json(new { success = false, message = "Bạn cần đăng nhập để thêm sản phẩm vào giỏ hàng. Vui lòng đăng nhập và thử lại." });
            }

            int accountId = currentAccount.id;
            MyDataDataContext Data = new MyDataDataContext();
            var existingCart = Data.GioHangs.FirstOrDefault(g => g.id == accountId);

            string cartId = "";

            if (existingCart == null)
            {
                cartId = GenerateRandomCartId();
                var newCart = new GioHang
                {
                    MaGioHang = cartId,
                    id = accountId
                };
                Data.GioHangs.InsertOnSubmit(newCart);
                Data.SubmitChanges();
            }
            else
            {
                cartId = existingCart.MaGioHang;
            }

            string strId = id.ToString();
            var existingCartItem = Data.ChiTietGioHangs.FirstOrDefault(c => c.MaGioHang == cartId && c.MaSanPham == strId);

            if (existingCartItem == null)
            {
                var product = Data.SanPhams.FirstOrDefault(p => p.MaSanPham == id);
                var khuyenMai = Data.ChiTietKhuyenMais
                                .Where(ct => ct.MaSanPham == product.MaSanPham)
                                .Join(Data.KhuyenMais,
                                      ct => ct.MaVoucher,
                                      km => km.MaVoucher,
                                      (ct, km) => new
                                      {
                                          KhuyenMai = km,
                                          ChiTietKhuyenMai = ct
                                      })
                                .FirstOrDefault();


                int productPrice = product.Gia;
                if (khuyenMai != null && KiemTraKhuyenMai(khuyenMai.KhuyenMai))
                {
                    // Nếu có khuyến mãi, giảm giá
                    productPrice -= (productPrice * khuyenMai.KhuyenMai.PhanTramGiam) / 100;
                }
                if (product != null)
                {
                    var newCartItem = new ChiTietGioHang
                    {
                        MaGioHang = cartId,
                        MaSanPham = strId,
                        SoLuong = quantity, 
                        ThanhTien = productPrice * quantity 
                    };

                    Data.ChiTietGioHangs.InsertOnSubmit(newCartItem);
                    Data.SubmitChanges();

                    // Cập nhật tổng số lượng sản phẩm trong giỏ hàng
                    var cartItems = Data.ChiTietGioHangs.Where(c => c.MaGioHang == cartId);
                    int updatedCartItemCount = cartItems.Select(c => c.MaSanPham).Distinct().Count();


                    return Json(new { success = true, message = "Đã thêm sản phẩm vào giỏ hàng!", cartItemCount = updatedCartItemCount });
                }
                else
                {
                    return Json(new { success = false, message = "Không tìm thấy sản phẩm." });
                }

NoiThatViet_Nhom3/NoiThatViet_Nhom3/NoiThatViet_Nhom3/Controllers/DonHangController.cs
using NoiThatViet_Nhom3.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NoiThatViet_Nhom3.Controllers
{
    public class DonHangController : Controller
    {
        // GET: DonHang
        [HandleError]
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult DonMua()
        {
            MyDataDataContext Data = new MyDataDataContext();

            var currentAccount = (TaiKhoan)Session["TaiKhoan"];
            int accountId = currentAccount.id;

            // Truy vấn để lấy MaGioHang từ TaiKhoanId
            var maGioHang = Data.GioHangs
                                .Where(gh => gh.id == accountId)
                                .Select(gh => gh.MaGioHang)
                                .FirstOrDefault();

            if (maGioHang != null)
            {
                // Truy vấn để lấy MaDH từ MaGioHang
                var maDHs = Data.ChiTietDonHangs
                                .Where(ct => ct.MaGioHang == maGioHang)
                                .Select(ct => ct.MaDH)
                                .ToList();

                var donHangs = Data.DonHangs
                                .Where(dh => maDHs.Contains(dh.MaDH))
                                .Select(dh => new DonHangViewModel
                                {
                                    MaDH = dh.MaDH,
                                    NgayLap = dh.NgayLap,
                                    TongTien = dh.TongTien,
                                    TrangThaiDH = dh.TrangThaiDH,
                                    TenSanPham = string.Join(", ", Data.ChiTietDonHangs
                                                                .Where(ct => ct.MaDH == dh.MaDH)
                                                                .Join(Data.SanPhams, ct => ct.MaSanPham, sp => sp.MaSanPham, (ct, sp) => sp.TenSanPham)
                                                                .ToList()),
                                    ThongTinDH = dh.ThongTinDH
                                })
                                .ToList();


                return View(donHangs);
            }
            return View(new List<DonHangViewModel>());
        }
    }
}

NoiThatViet_Nhom3/NoiThatViet_Nhom3/NoiThatViet_Nhom3/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet">
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" />
    <link rel="stylesheet" type="text/css" href="~/Content/StyleForLayout.css" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" rel="stylesheet" />
    <style>

        .menu-item-text {
            color: #000000;
            text-decoration: none;
        }

        .no-underline {
            text-decoration: none;
        }
    </style>
</head>
<body>
    <script src="~/Content/XuLyGoiYSanPham.js"></script>
    @{ var user = Session["TaiKhoan"] as NoiThatViet_Nhom3.Models.TaiKhoan;}
    @{ var userFB = Session["TaiKhoanFB"] as NoiThatViet_Nhom3.Models.ThongTinCaNhan;}

    <nav>
        <ul class="menu">
            <li class="menu-item"><a href="/" class="logo-link"><img src="~/Content/images/logo.jpg" alt="Logo"></a></li>
            <li class="menu-item-text">
                <i class="bi bi-list"></i>
                @NoiThatViet_Nhom3.Resources.Messages.Featured_Categorie
            </li>
            <li class="menu-item-text">
                @Html.Action("menu", "SanPham")
            </li>
            <li class="menu-item-text">
                @Html.Action("Phong", "SanPham")
            </li>
            <li class="menu-item-text">
                @Html.Action("DichVu", "SanPham")
            </li>
            <li class="menu-item-text">
                <a>@NoiThatViet_Nhom3.Resources.Messages.Contact</a>
                <ul>
                    <li><a href="#">Gmail</a></li>
                    <li><a href="#">Số điện thoại</a></li>
                    <li><a href="#">Địa chỉ</a></li>
                </ul>
            </li>
            <li class="menu-item-text">
                <form action="/SanPham/Search" method="get" class="form-inline my-2 my-lg-0">
                    <div class="search-container">
                        <input class="form-control mr-sm-2 search-input"
                               type="text"
                               name="searchString"
                               placeholder="  @NoiThatViet_Nhom3.Resources.Messages.Find_products">
                        <button type="submit" class="search-button">
                            <i class="fa fa-search"></i>
                        </button>
                        <ul class="search-suggestions"></ul>
                    </div>
                </form>
            </li>
            <li class="menu-item-text">
                <a href="@Url.Action("Index", "Cart", new { userId = Session["UserId"] })">
                    <i class="bi bi-handbag"></i>
                    <span class="icon-text"></span>
            </li>


            <li class="menu-item-text">
                <a href="@Url.Action("Wishlist", "SanPham", new { userId = Session["UserId"] })">
                    <i class="bi bi-heart"></i>
                </a>
                @if (ViewBag.WishlistCount > 0)
                {
                    <span class="badge badge-warning wishlist-count">@ViewBag.WishlistCount</span>
                }
            </li>
            <li class="menu-item-text">
                <a href="#">@NoiThatViet_Nhom3.Resources.Messages.Language</a>
                <ul>
                    <li><a href="@Url.Action("ChangeLanguage", "Language", new { selectedLanguage = "en" })">English</a></li>
                    <li><a href="@Url.Action("ChangeLanguage", "Language", new { selectedLanguage = "vi" })">Tiếng Việt</a></li>
                </ul>
            </li>
            @{
                var isLoggedIn = (user != null) || (userFB != null);
            }
            @{ if (!isLoggedIn)
                {
                        <li class="menu-item-text">
                            @Html.Raw("<i class='bi bi-person'></i>") @Html.ActionLink(@NoiThatViet_Nhom3.Resources.Messages.Login, "DangNhap", "Home", null, new { @class = "menu-item-text" })
                        </li>
                }
                else
                {
                    <li class="menu-item-text" id="dropdownMenu">
                        <a href="#" class="no-underline" id="navbarDropdown" onmouseover="showDropdownMenu()">
                            @(user != null ? user.ThongTinCaNhan.HoTen : userFB.HoTen)
                        </a>
                        <div class="dropdown-content" id="dropdownContent">
                            <a href="@Url.Action("ThongTinTK", "Home")">Thông tin tài khoản</a>
                            <a href="@Url.Action("DonMua", "DonHang")">Đơn mua</a>
                            <a href="#" onclick="confirmLogout()">Đăng xuất</a>
                            <form id="logoutForm" action="@Url.Action("DangXuat", "Home")" method="post" style="display: none;">
                                @Html.AntiForgeryToken()
                            </form>

                        </div>
                    </li>
                }
            }
        </ul>
    </nav>
    <div class="container-fluid">
        @RenderBody()
    </div>

    <footer class="footer spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-6 col-sm-6">
                    <div class="footer__about">
                        <div class="footer__about__logo">
                            <a href="/" class="logo-link"><img src="~/Content/images/logo.jpg" alt="Logo"></a>
                        </div>
                        <ul>
                            <li>Địa chỉ: 838 Nguyễn Kiệm,<br>Phường 3, Gò Vấp, Tp.HCM</li>
                            <li>SĐT: 0368285760</li>
                            <li>Email: nghia812014@gmail.com</li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-4 col-md-6 col-sm-6 offset-lg-1">
                    <div class="footer__widget">
                        <h6>Liên kết hữu ích</h6>
                        <ul>
                            <li><a href="#">Chính sách bán hàng</a></li>
                            <li><a href="#">Chính sách giao hàng & lắp đặt</a></li>
                            <li><a href="#">Chính sách đổi trả</a></li>
                            <li><a href="#">Chính sách bảo hành & bảo trì</a></li>
                            <li><a href="#">Khách hàng thân thiết - MOHOmie</a></li>
                            <li><a href="#">Khuyến mãi</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-4 col-md-12">
                    <div class="footer__widget">
                        <h6>Tham gia với chúng tôi ngay bây giờ</h6>
                        <p>Nhận thông tin mới nhất của cửa hàng cập nhật qua Email</p>
                        <form action="#">
                            <input type="text" placeholder="Nhập Email tại đây">
                            <button type="submit" class="site-btn">Đăng ký ngay</button>
                        </form>
                        <div class="footer__widget__social">
                            <a href="#"><i class="fa fa-facebook"></i></a>
                            <a href="#"><i class="fa fa-instagram"></i></a>
                            <a href="#"><i class="fa fa-twitter"></i></a>
                            <a href="#"><i class="fa fa-pinterest"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <script>
        function confirmLogout() {
            if (confirm("Bạn có muốn đăng xuất không?")) {
                document.getElementById('logoutForm').submit();
            }
        }

    </script>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)


</body>
</html>